import { c } from './colors.js';

export function renderHelp(): string {
  return [
    `${c.bold('c2si')} ${c.gray('— carbon → silicon language compressor')}`,
    ``,
    `${c.bold('USAGE')}`,
    `  c2si ${c.cyan('[command]')} ${c.yellow('[options]')} ${c.gray('[text]')}`,
    `  ${c.gray('echo "text" | c2si')}`,
    ``,
    `${c.bold('COMMANDS')}`,
    `  ${c.cyan('compress')}   Tier 1 rule-based compression ${c.dim('(default, no model needed)')}`,
    `  ${c.cyan('count')}      Print GPT-4 BPE token count of input`,
    `  ${c.cyan('hyper')}      Tier 3 HyperSCN ${c.dim('(requires --provider and --model)')}`,
    ``,
    `${c.bold('OPTIONS')}`,
    `  ${c.yellow('--domain')} ${c.dim('<d>')}       finance | legal | code | medical`,
    `  ${c.yellow('--provider')} ${c.dim('<p>')}     ollama | openai`,
    `  ${c.yellow('--model')} ${c.dim('<m>')}        e.g. llama3.2:3b, gpt-4o-mini`,
    `  ${c.yellow('--base-url')} ${c.dim('<u>')}     OpenAI-compatible endpoint URL`,
    `  ${c.yellow('--json')}              Machine-readable JSON ${c.green('(agent-friendly)')}`,
    `  ${c.yellow('--stats')}             Print compression stats to stderr`,
    `  ${c.yellow('--quiet')}             Suppress spinners`,
    `  ${c.yellow('--no-preamble')}       (hyper) Omit the decoder preamble`,
    `  ${c.yellow('--help')}              Show help`,
    `  ${c.yellow('--version')}           Show version`,
    ``,
    `${c.bold('ENV VARS')}`,
    `  ${c.magenta('OPENAI_API_KEY')}       API key for OpenAI / compatible providers`,
    `  ${c.magenta('OPENAI_BASE_URL')}      Override base URL for openai provider`,
    `  ${c.magenta('OLLAMA_HOST')}          Ollama server URL ${c.dim('(default http://localhost:11434)')}`,
    `  ${c.magenta('C2SI_PROVIDER')}        Default provider`,
    `  ${c.magenta('C2SI_MODEL')}           Default model`,
    `  ${c.magenta('NO_COLOR')}             Disable ANSI colors`,
    ``,
    `${c.bold('EXAMPLES')}`,
    `  $ c2si "In order to effectively address the challenges"`,
    `  $ cat document.txt | c2si`,
    `  $ c2si --json "text"    ${c.gray('# {"compressed":"text","ratio":1,...}')}`,
    `  $ c2si hyper --provider=ollama --model=llama3.2:3b < long.md`,
    `  $ c2si count "Hello world"`,
    ``,
    `${c.bold('EXIT CODES')}`,
    `  0 ok · 1 input error · 2 config error · 3 adapter error`,
    ``,
    `${c.dim('docs:')} ${c.underline('https://github.com/sjhddh/C2Si')}`,
    ``,
  ].join('\n');
}
